- hosts: aws
  become: yes
  become_user: root
  tasks:
    - file:
        path: /opt/tomcat
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: 0755
    - yum:
        name: java-1.8.0-openjdk-devel
        state: latest

- hosts: aws
  tasks:
    - unarchive:
        src: http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.32/bin/apache-tomcat-8.5.32.tar.gz
        dest: /opt/tomcat
        remote_src: yes
    - shell: ls -ltr /opt/tomcat/apache-tomcat-8.5.32/bin
      register: toto
    - debug: var=toto
    - local_action: maven_artifact
      args:
        group_id: fr.xebia
        artifact_id: clickCount
        version: 1.0-SNAPSHOT
        extension: war
        repository_url: "http://localhost:8081/artifactory/example-repo-local"
        dest: /tmp/clickCount.war
    - copy:
        src: /tmp/clickCount.war
        dest: /opt/tomcat/apache-tomcat-8.5.32/webapps
    - shell: /opt/tomcat/apache-tomcat-8.5.32/bin/startup.sh