- hosts: aws
  become: yes
  become_user: root
  tasks:
    - file:
        path: /opt/tomcat
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: 0755

- hosts: aws
  tasks:
    - unarchive:
        src: http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.32/bin/apache-tomcat-8.5.32.tar.gz
        dest: /opt/tomcat
        remote_src: yes
    - shell: ls -ltr /opt/tomcat
      register: toto
    - debug: var=toto
    - maven_artifact:
        group_id: fr.xebia
        artifact_id: clickCount
        version: 1.0-SNAPSHOT
        dest: /opt/tomcat/apache-tomcat-8.5.32/webapps