- hosts: aws
  become: yes
  become_user: root
  tasks:
    - shell: nohup /opt/tomcat/apache-tomcat-8.5.32/bin/shutdown.sh &
    - file:
        path: /opt/tomcat
        state: absent
    - file:
        path: /opt/tomcat
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: 0755
    - yum:
        name: java-1.8.0-openjdk-devel
        state: latest

- hosts: aws
  tasks:
    - unarchive:
        src: http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.32/bin/apache-tomcat-8.5.32.tar.gz
        dest: /opt/tomcat
        remote_src: yes
    - shell: ls -ltr /opt/tomcat/apache-tomcat-8.5.32/conf/server.xml
      register: toto
    - debug: var=toto
    - local_action: maven_artifact
      args:
        group_id: fr.xebia
        artifact_id: applicatif
        version: 1.0-SNAPSHOT
        extension: tar
        repository_url: "http://localhost:8081/artifactory/example-repo-local"
        dest: /tmp/applicatif.tar
    - unarchive:
        src: /tmp/applicatif.tar
        dest: /opt/tomcat/apache-tomcat-8.5.32/
    - local_action: file
      args:
        path: /tmp/applicatif
        state: directory
    - local_action: unarchive
      args:
        src: /tmp/applicatif.tar
        dest: /tmp/applicatif/
    - template:
        src: "/tmp/applicatif/{{ item }}"
        dest: "/opt/tomcat/apache-tomcat-8.5.32/{{ item }}"
      with_items:
        - "conf/server.xml"
        - "properties/redis.properties"
    - local_action: file
      args:
        path: "/tmp/{{ item }}"
        state: absent
      with_items:
        - "applicatif.tar"
        - "applicatif/"

- hosts: aws
  become: yes
  become_user: root
  tasks:
    - shell: nohup /opt/tomcat/apache-tomcat-8.5.32/bin/startup.sh &